### ISSUE TITLE
Update README.md with examples

### ISSUE THREAD

**Issue by sanders41** [pbs-data-solutions/prelude-parser#21]
The README needs to be updated with examples how how to use the functions. This should include `parse_flat_file` and `to_dataframe`. The examples can be pulled form the doc strings.

**Comment by ponita-tan** [comment]
Hi, can i make a contribute to this issue?

**Comment by sanders41** [comment]
Sure!

**Comment by sanders41** [comment]
An update here. `parse_flat_file` has been renamed to `parse_to_classes`. In addition new `parse_to_dict`, and polars `to_dataframe` functions had been added. All have examples in the doc strings. I don't have any more updates/additions planned for now.
